export const PROPERTIES_PATTERNS = [
  /propert[iy1]es/i,
  /file\s*folder|type:\s*file\s*folder/i,
  /size\s*on\s*disk|contains:?\s*\d+\s*files/i,
  /attributes:?\s*read[- ]?only/i,
  /eigenschaften/i,
  /propri[eé]t[eé]s/i,
  /propiedades/i,
  /propriet[aà]/i,
  /propriedades/i,
  /свойства/i,
  /w[lł]a[sś]ciwo[sś]ci/i,
  /vlastnost/i,
  /属性|プロパティ/i,
  /steamapps\s*[\\\/]\s*common/i,
  /program\s*files\s*[\\\/]\s*steam/i,
];

export const WUB_PATTERNS = [
  /disable\s*updates?|enable\s*updates?/i,
  /apply\s*now/i,
  /\bstatus\b/i,
  /protect\s*services?\s*settings?/i,
  /windows\s*update\s*blocker\s*v?1\.?0/i,
  /windows\s*updates?\s*paused/i,
  /updates?\s*paused/i,
  /\bwub\b/i,
  /windows\s*update\s*blocker|update\s*blocker/i,
  /\bblocker\b/i,
  /update[s]?\s*paus[iíeé]/i,
  /(windows[- ]?)?updates?\s*pausiert/i,
  /updates?\s*wstrzymane/i,
  /mise\s*[aà]\s*jour\s*.*paus/i,
  /actualizaci[oó]n\s*.*paus/i,
  /aggiornamenti\s*.*sospes/i,
  /atualiza[cç][aã]o\s*.*paus/i,
  /(windows\s*)?updates?\s*gepauzeerd/i,
  /pozastavene\s*aktualizacie/i,
  /aktualiz[aá]ci[ae]\s*.*pozastaven/i,
  /pozastaven[eé]\s*.*aktualiz/i,
  /vypn[uú][tť]\s*aktualiz/i,
  /[uú]rove[nň]\s*slu[zž]by|slu[zž]ieb/i,
  /možnosti\s*windows|windows\s*aktualiz/i,
  /aktualiz[aá]ci[eéí]|[ao]liz[aá]ci/i,
  /暂停|已暂停|更新.*暂停/i,
  /一時停止|更新.*停止/i,
];
